export { ItinerariesList } from './itinerarieslist/ItinerariesList'
export { CompareTrips } from './stages/compareTrips/CompareTrips'
export { Confirmation } from './stages/confirmation/Confirmation'
export { EditTrip } from './stages/editTrip/EditTrip'
export { Review } from './stages/reviewTrip/ReviewTrip'